// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SecretPassage","status":true,"description":"The SecretPassage plugin allows you to make an otherwise impassable tile passable through the use of regions.","parameters":{"Passable":"1","Impassable":"2","Invisible":"3"}}
];
