// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TroopEmergesMessage","status":true,"description":"Change the content of the %1 var for Emerge message to Troop name instead of the 1st enemy name.","parameters":{}}
];
